"""Add country and password fields to Account model

Revision ID: 519b280786e2
Revises: 
Create Date: 2024-11-13 18:09:42.940092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519b280786e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=64), nullable=False))  # Add country field
        batch_op.add_column(sa.Column('password', sa.String(length=50), nullable=False))  # Add password field
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=3),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)
        batch_op.drop_column('password')  # Drop password field
        batch_op.drop_column('country')  # Drop country field

    # ### end Alembic commands ###